version: '3'

services:
  janus:
    image: janusgraph/janusgraph:0.3.2
    ports:
      - "8182:8182"
    container_name: janusgraph
    environment:
      gremlinserver.maxContentLength: 999999
      gremlinserver.scriptEvaluationTimeout: 10600
      janusgraph.query.force-index: "false"
      janusgraph.query.smart-limit: "false"
      janusgraph.storage.backend: cql
      janusgraph.storage.hostname: scylladb
      janusgraph.index.search.backend: elasticsearch
      janusgraph.index.search.hostname: elasticsearch
    depends_on:
      - scylladb
      - elasticsearch

  scylladb:
    image: scylladb/scylla:3.0.7
    container_name: scylladb
    ports:
     # http://docs.scylladb.com/kb/posix/
     # REST API
     - "10000:10000"
     # CQL ports (native_transport_port)
     - "9042:9042"
     # Thrift (rpc_port)
     - "9160:9160"
     # Internode
     - "7000:7000"
     - "7001:7001"
     # JMX
     - "7199:7199"
     # Prometheus monitoring
     - "9180:9180"
     - "9100:9100"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: '--experimental 1'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    ports:
     - "9200:9200"
    environment:
      - discovery.type=single-node
    user: "1000"

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.3.2"
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']